server:
  port: 8888
  use-forward-headers: true
  tomcat:
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For

spring:
  cloud.loadbalancer.ribbon.enabled: false

eureka:
  instance:
    preferIpAddress: true